name: animely
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # auth:
  #   path: C://Users/ASUS/Desktop/Packages/auth/auth

  flutter:
    sdk: flutter

  flutter_riverpod: ^0.14.0+3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.4
  riverpod: ^0.14.0+3
  visibility_detector: ^0.2.2
  path_provider: ^2.0.6 #n
  shared_preferences: ^2.0.8
  flutter_downloader: ^1.7.1 #n
  wakelock: ^0.5.6 #n
  cached_network_image: #n
  flutter_staggered_grid_view:
  connectivity_plus: ^2.0.2
  permission_handler: ^8.2.5 #n
  freezed_annotation: ^0.14.2
  fijkplayer: ^0.10.0
  fijkplayer_skin: ^2.2.8
  flick_video_player: ^0.3.1
  video_player: ^2.2.7
  flutter_local_notifications: ^8.2.0 #n
  file_picker: ^4.2.4
  flutter_android_pip: ^0.0.2
  webview_flutter: ^3.0.0
  faker: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  rename: ^2.0.1
  freezed: ^0.14.5
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.0
  hive_generator: ^1.1.1
  build_runner: ^2.1.2
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/flutter_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
